## Table of Contents

- Examples of Two Dimensions(2D) Tensors
- Tensor Creation in 2D
- Indexing and Slicing in 2D
- Basic Operations 

### Examples of Two Dimensions(2D) Tensors

In [7]:
import torch

a = [[11,12,13], [21,22,23], [31,32,33]]

A = torch.tensor(a)
print(A)
print(A.ndimension())
print(A.shape)
print(A.numel())

tensor([[11, 12, 13],
        [21, 22, 23],
        [31, 32, 33]])
2
torch.Size([3, 3])
9


### Basic Operations

In [8]:
X = torch.tensor([[1,0],[0,1]])
Y = torch.tensor([[2,1],[1,2]])
Z = X + Y
print(Z)

tensor([[3, 1],
        [1, 3]])


In [10]:
Y = torch.tensor([[2,1],[1,2]])
Z = 2*Y
print(Z)

tensor([[4, 2],
        [2, 4]])


In [11]:
Z = X*Y
print(Z)

tensor([[2, 0],
        [0, 2]])


In [12]:
A = torch.tensor([[0,1,1],[1,0,1]])
B = torch.tensor([[1,1],[1,1],[-1,1]])
C = torch.mm(A,B)
print(C)

tensor([[0, 2],
        [0, 2]])
